const statusLabels: Record<string, string> = {
  draft: "작성 중",
  submitted: "승인 대기",
  approved: "승인됨",
  posted: "확정",
  cancelled: "취소",
  active: "운영 중",
  maintenance: "점검 중",
  retired: "퇴역",
  open: "접수",
  in_progress: "처리 중",
  waiting: "대기",
  resolved: "해결",
  closed: "종료",
  low: "4 · 낮음",
  normal: "3 · 보통",
  high: "2 · 높음",
  critical: "1 · 긴급",
  none: "기한 없음",
  on_track: "기한 정상",
  at_risk: "기한 임박",
  overdue: "기한 초과",
  stopped: "SLA 종료",
  covered: "지원 정상",
  expiring: "갱신 필요",
  renewal_90: "90일 내 갱신",
  renewal_60: "60일 내 갱신",
  renewal_30: "30일 내 갱신",
  expires_today: "오늘 만료",
  expired: "지원 만료",
  not_contracted: "미계약",
  vendor_gap: "벤더 지원 공백",
  vendor_unverified: "벤더 계약 미확인",
  unknown: "미등록",
  scheduled: "예정",
  completed: "완료",
  issue_found: "조치 필요",
  healthy: "정상",
  warning: "주의",
  pass: "PASS",
  fail: "FAIL",
  na: "N/A",
  ha: "HA",
  ft: "FT",
  mixed: "HA + FT",
  unprotected: "미보호",
  standby: "대기",
  fault: "장애",
  faulted: "장애",
  offline: "오프라인",
  running: "실행 중",
  degraded: "성능 저하",
  up: "UP",
  down: "DOWN",
  perpetual: "영구",
  subscription: "구독",
  oem: "OEM",
  trial: "평가판",
  suspended: "중지",
  other: "기타",
};

export function StatusBadge({ status }: { status: string }) {
  return <span className={`status-badge status-${status}`}>{statusLabels[status] ?? status}</span>;
}
