const statusLabels: Record<string, string> = {
  draft: "작성 중",
  submitted: "승인 대기",
  approved: "승인됨",
  posted: "확정",
  cancelled: "취소",
  active: "운영 중",
  maintenance: "점검 중",
  retired: "폐기",
  open: "접수",
  in_progress: "처리 중",
  waiting: "대기",
  resolved: "해결",
  closed: "종료",
  low: "낮음",
  normal: "보통",
  high: "높음",
  critical: "긴급",
  covered: "지원 정상",
  expiring: "갱신 필요",
  expired: "지원 만료",
  not_contracted: "미계약",
  unknown: "미등록",
  scheduled: "예정",
  completed: "완료",
  issue_found: "조치 필요",
  healthy: "정상",
  warning: "주의",
  pass: "PASS",
  fail: "FAIL",
  na: "N/A",
};

export function StatusBadge({ status }: { status: string }) {
  return <span className={`status-badge status-${status}`}>{statusLabels[status] ?? status}</span>;
}
